---
manus_revo3_retarget:
  ros__parameters:
    legacy_left_physical_index_spread_offset_deg: 15.0
    legacy_left_physical_middle_spread_offset_deg: 15.0
    legacy_left_physical_ring_spread_offset_deg: 15.0
    legacy_left_physical_pinky_spread_offset_deg: 15.0
    legacy_left_physical_index_spread_scale: -1.0
    legacy_left_physical_middle_spread_scale: -1.0
    legacy_left_physical_ring_spread_scale: -1.0
    legacy_left_physical_pinky_spread_scale: -1.0
    legacy_left_physical_middle_spread_dynamic: true
    legacy_left_physical_ring_spread_forward_scale: 1.0
    legacy_left_physical_ring_spread_backward_scale: 1.0
    legacy_right_physical_index_spread_offset_deg: 15.0
    legacy_right_physical_middle_spread_offset_deg: -5.0
    legacy_right_physical_ring_spread_offset_deg: -5.0
    legacy_right_physical_pinky_spread_offset_deg: 0.0
    legacy_right_physical_index_spread_scale: -1.0
    legacy_right_physical_middle_spread_scale: -1.0
    legacy_right_physical_ring_spread_scale: -1.0
    legacy_right_physical_pinky_spread_scale: -1.0
    legacy_right_physical_middle_spread_dynamic: true
    legacy_right_physical_ring_spread_forward_scale: 1.0
    legacy_right_physical_ring_spread_backward_scale: 1.0
    physical_left_little_MPR_joint_scale: 1.0
    physical_left_little_MPR_joint_offset_deg: 0.0
    physical_left_ring_MPR_joint_scale: 1.0
    physical_left_ring_MPR_joint_offset_deg: 0.0
    physical_left_middle_MPR_joint_scale: 1.0
    physical_left_middle_MPR_joint_offset_deg: 0.0
    physical_left_index_MPR_joint_scale: 1.0
    physical_left_index_MPR_joint_offset_deg: 0.0
    physical_right_little_MPR_joint_scale: 1.0
    physical_right_little_MPR_joint_offset_deg: 0.0
    physical_right_ring_MPR_joint_scale: 1.0
    physical_right_ring_MPR_joint_offset_deg: 0.0
    physical_right_middle_MPR_joint_scale: 1.0
    physical_right_middle_MPR_joint_offset_deg: 0.0
    physical_right_index_MPR_joint_scale: 1.0
    physical_right_index_MPR_joint_offset_deg: 0.0
